development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  host: localhost
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  host: localhost
  username: postgres
  password: password
